description: Reads data from the terminal (or the DATA env var) and emits it as an Arrow output.
repo: https://github.com/dora-rs/dora-hub
owners:
  - bobdingAI
  - haixuanTao
  - heyong4725
  - phil-opp
