description: Captures RGB color and depth frames from an Orbbec depth camera via the pyorbbecsdk.
repo: https://github.com/dora-rs/dora-hub
owners:
  - bobdingAI
  - haixuanTao
  - heyong4725
  - phil-opp
